### ISSUE TITLE
Error when trying to add resources

### ISSUE THREAD

**Issue by wenzelrehub** [AshotN/adminjs-feathers#3]
I tried to add AdminJS to my Feathers app by applying everything from https://github.com/AshotN/feathers-chat-AdminJS/commit/49f8e5c2f335c4d0bca04e26d60d3d2e8b90be75.

With an empty resource array in `feathers-chat-ts/src/adminjs.ts`, the AdminJS frontend is loading correctly.
As soon as I try to add a resource I get an HTTP 500 Error and the following console output:

``` 
error <ref *1> ResourceDecorator {
  getPropertyByKey: [Function: bound getPropertyByKey],
  _resource: Resource {
    _decorated: [Circular *1],
    propsObject: { _id: [Property], text: [Property] },
    service: FeedbackService {
      update: [Function],
      find: [Function],
      get: [Function],
      create: [Function],
      patch: [Function],
      remove: [Function],
      hooks: [Function (anonymous)],
      _events: undefined,
      _eventsCount: 0,
      _maxListeners: undefined,
      setMaxListeners: [Function: setMaxListeners],    
      getMaxListeners: [Function: getMaxListeners],    
      emit: [Function: emit],
      addListener: [Function: addListener],
      on: [Function: addListener],
      prependListener: [Function: prependListener],    
      once: [Function: once],
      prependOnceListener: [Function: prependOnceListener],
      removeListener: [Function: removeListener],
      off: [Function: removeListener],
      removeAllListeners: [Function: removeAllListeners],
      listeners: [Function: listeners],
      rawListeners: [Function: rawListeners],
      listenerCount: [Function: listenerCount],
      eventNames: [Function: eventNames]
    },
    schema: {
      '$id': 'Feedback',
      additionalProperties: false,
      type: 'object',
      properties: [Object],
      required: [Array]
    }
  },
  _admin: AdminJS {
    resources: [ [Resource] ],
    options: {
      rootPath: '/admin',
      logoutPath: '/admin/logout',
      loginPath: '/admin/login',
      databases: [],
      resources: [Array],
      dashboard: {},
      pages: {},
      bundler: {}
    },
    locale: { translations: [Object], language: 'en' },
    translateFunctions: {
      translateAction: [Function: translateAction],
      ta: [Function: translateAction],
      translateButton: [Function: translateButton],
      tb: [Function: translateButton],
      translateLabel: [Function: translateLabel],
      tl: [Function: translateLabel],
      translateProperty: [Function: translateProperty],
      tp: [Function: translateProperty],
      translateMessage: [Function: translateMessage],
      tm: [Function: translateMessage],
      t: [Function: bound t],
      translate: [Function: bound t]
    },
    translateAction: [Function: translateAction],
    ta: [Function: translateAction],
    translateButton: [Function: translateButton],
    tb: [Function: translateButton],
    translateLabel: [Function: translateLabel],
    tl: [Function: translateLabel],
    translateProperty: [Function: translateProperty],
    tp: [Function: translateProperty],
    translateMessage: [Function: translateMessage],
    tm: [Function: translateMessage],
    t: [Function: bound t],
    translate: [Function: bound t],
    componentLoader: ComponentLoader { components: {} }
  },
  h: ViewHelpers {
    options: {
      rootPath: '/admin',
      logoutPath: '/admin/logout',
      loginPath: '/admin/login',
      databases: [],
      resources: [Array],
      dashboard: {},
      pages: {},
      bundler: {}
    }
  },
  options: { properties: {} },
  properties: {
    _id: PropertyDecorator {
      property: [Property],
      _admin: [AdminJS],
      _resource: [Circular *1],
      propertyPath: '_id',
      isVirtual: false,
      virtualSubProperties: [],
      options: {}
    },
    text: PropertyDecorator {
      property: [Property],
      _admin: [AdminJS],
      _resource: [Circular *1],
      propertyPath: 'text',
      isVirtual: false,
      virtualSubProperties: [],
      options: {}
    }
  },
  actions: {
    new: ActionDecorator {
      name: 'new',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    list: ActionDecorator {
      name: 'list',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    show: ActionDecorator {
      name: 'show',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    edit: ActionDecorator {
      name: 'edit',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    delete: ActionDecorator {
      name: 'delete',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    bulkDelete: ActionDecorator {
      name: 'bulkDelete',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    },
    search: ActionDecorator {
      name: 'search',
      _admin: [AdminJS],
      _resource: [Resource],
      h: [ViewHelpers],
      action: [Object]
    }
  }
}

  TypeError: Cannot read properties of undefined (reading 'split')
      at formatName (node_modules\adminjs\lib\utils\translate-functions.factory.js:12:33)
      at translate (node_modules\adminjs\lib\utils\translate-functions.factory.js:18:25)
      at AdminJS.translateLabel (node_modules\adminjs\lib\utils\translate-functions.factory.js:37:58)
      at ResourceDecorator.getResourceName (node_modules\adminjs\lib\backend\decorators\resource\resource-decorator.js:92:24)
      at ResourceDecorator.toJSON (node_modules\adminjs\lib\backend\decorators\resource\resource-decorator.js:289:18)
      at node_modules\adminjs\lib\frontend\store\initialize-store.js:25:34 
      at Array.map (<anonymous>)
      at initializeStore (node_modules\adminjs\lib\frontend\store\initialize-store.js:23:68)
      at html (node_modules\adminjs\lib\frontend\layout-template.js:34:50) 
      at AppController.index (node_modules\adminjs\lib\backend\controllers\app-controller.js:27:40)
```

**Comment by AshotN** [comment]
Can you share the resource file, and the service file.

**Comment by wenzelrehub** [comment]
Resources/Feedback.ts
```typescript
import { ResourceWithOptions } from "adminjs";
import { feedbackSchema } from "../services/feedback/feedback.schema";
import { app } from "../app";

export const FeedbackResource: ResourceWithOptions = {
  resource: { service: app.service("feedback"), schema: feedbackSchema },

  options: {},
};
```

services/feedback/feedback.schema
```typescript
// // For more information about this file see https://dove.feathersjs.com/guides/cli/service.schemas.html
import { resolve } from "@feathersjs/schema";
import { Type, getValidator, querySyntax } from "@feathersjs/typebox";
import type { Static } from "@feathersjs/typebox";

import type { HookContext } from "../../declarations";
import { dataValidator, queryValidator } from "../../validators";
import { newUUID } from "../../resolvers/new-uuids";

// Main data model schema
export const feedbackSchema = Type.Object(
  {
    _id: Type.String(),
    text: Type.String(),
  },
  { $id: "Feedback", additionalProperties: false }
);
export type Feedback = Static<typeof feedbackSchema>;
export const feedbackValidator = getValidator(feedbackSchema, dataValidator);
export const feedbackResolver = resolve<Feedback, HookContext>({});

export const feedbackExternalResolver = resolve<Feedback, HookContext>({});

// Schema for creating new entries
export const feedbackDataSchema = Type.Pick(feedbackSchema, ["text"], {
  $id: "FeedbackData",
});
export type FeedbackData = Static<typeof feedbackDataSchema>;
export const feedbackDataValidator = getValidator(
  feedbackDataSchema,
  dataValidator
);
export const feedbackDataResolver = resolve<Feedback, HookContext>({
  _id: newUUID,
});

// Schema for updating existing entries
export const feedbackPatchSchema = Type.Partial(feedbackSchema, {
  $id: "FeedbackPatch",
});
export type FeedbackPatch = Static<typeof feedbackPatchSchema>;
export const feedbackPatchValidator = getValidator(
  feedbackPatchSchema,
  dataValidator
);
export const feedbackPatchResolver = resolve<Feedback, HookContext>({});

// Schema for allowed query properties
export const feedbackQueryProperties = Type.Pick(feedbackSchema, [
  "_id",
  "text",
]);
export const feedbackQuerySchema = Type.Intersect(
  [
    querySyntax(feedbackQueryProperties),
    // Add additional query properties here
    Type.Object({}, { additionalProperties: false }),
  ],
  { additionalProperties: false }
);
export type FeedbackQuery = Static<typeof feedbackQuerySchema>;
export const feedbackQueryValidator = getValidator(
  feedbackQuerySchema,
  queryValidator
);
export const feedbackQueryResolver = resolve<FeedbackQuery, HookContext>({});
```

services/feedback/feedback.ts
```typescript
// For more information about this file see https://dove.feathersjs.com/guides/cli/service.html
import { authenticate } from "@feathersjs/authentication";

import { hooks as schemaHooks } from "@feathersjs/schema";

import {
  feedbackDataValidator,
  feedbackPatchValidator,
  feedbackQueryValidator,
  feedbackResolver,
  feedbackExternalResolver,
  feedbackDataResolver,
  feedbackPatchResolver,
  feedbackQueryResolver,
} from "./feedback.schema";

import type { Application } from "../../declarations";
import { FeedbackService, getOptions } from "./feedback.class";
import { feedbackPath, feedbackMethods } from "./feedback.shared";

export * from "./feedback.class";
export * from "./feedback.schema";

// A configure function that registers the service and its hooks via `app.configure`
export const feedback = (app: Application) => {
  // Register our service on the Feathers application
  app.use(feedbackPath, new FeedbackService(getOptions(app)), {
    // A list of all methods this service exposes externally
    methods: feedbackMethods,
    // You can add additional custom events to be sent to clients here
    events: [],
  });
  // Initialize hooks
  app.service(feedbackPath).hooks({
    around: {
      all: [
        authenticate("jwt"),
        schemaHooks.resolveExternal(feedbackExternalResolver),
        schemaHooks.resolveResult(feedbackResolver),
      ],
    },
    before: {
      all: [
        schemaHooks.validateQuery(feedbackQueryValidator),
        schemaHooks.resolveQuery(feedbackQueryResolver),
      ],
      find: [],
      get: [],
      create: [
        schemaHooks.validateData(feedbackDataValidator),
        schemaHooks.resolveData(feedbackDataResolver),
      ],
      patch: [
        schemaHooks.validateData(feedbackPatchValidator),
        schemaHooks.resolveData(feedbackPatchResolver),
      ],
      remove: [],
    },
    after: {
      all: [],
    },
    error: {
      all: [],
    },
  });
};

// Add this service to the service type index
declare module "../../declarations" {
  interface ServiceTypes {
    [feedbackPath]: FeedbackService;
  }
}
```

**Comment by AshotN** [comment]
It looks like you are using Mongo, which I have not really tested against. If I had to guess it's having a hard time figuring out where the `id` property is. I'll have to find some time to spin up a Mongo DB to test against. Or if you are willing to give it a shot to pinpoint the issue

**Comment by wenzelrehub** [comment]
There are still some things to tackle but at least this issue is solved by adding the `id` property to the resource options:
```typescript
import { ResourceWithOptions } from "adminjs";
import { feedbackSchema } from "../services/feedback/feedback.schema";
import { app } from "../app";

export const FeedbackResource: ResourceWithOptions = {
  resource: { service: app.service("feedback"), schema: feedbackSchema },

  options: {
    id: "feedback",
  },
};
```

**Comment by AshotN** [comment]
Ya that makes sense, need to add better docs in general.
